{
 "title": "single stock dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "active_stocks",
    "query": {
     "query": "label_values(active_stock_quage,symbol)"
    }
   },
   {
    "name": "id_of_buy_stock",
    "query": {
     "query": "label_values(active_stock_quage{symbol=\"$active_stocks\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Profit without taxes and transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum (stock_price{symbol=\"$active_stocks\"} * active_stock_quantity_quage{symbol=\"$active_stocks\"} - active_stock_quage{symbol=\"$active_stocks\"} * active_stock_quantity_quage{symbol=\"$active_stocks\"}) by (id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profit without transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum((stock_price{symbol=\"$active_stocks\"} * active_stock_quantity_quage{symbol=\"$active_stocks\"} - active_stock_quage{symbol=\"$active_stocks\"} * active_stock_quantity_quage{symbol=\"$active_stocks\"}) * 0.75) by (id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percantage out of my bag",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_stock_quage{symbol=\"$active_stocks\"} * active_stock_quantity_quage{symbol=\"$active_stocks\"})\n/\nsum(sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"}))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Time series  $active_stocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "id_of_buy_stock" },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(stock_price{id=~\"$id_of_buy_stock\"}) by (id,date,start_price)",
     "legendFormat": "{{date}} -- {{ start_price}}"
    },
    {
     "expr": "sum(active_stock_quage{id=~\"$id_of_buy_stock\"}) by (id,date,start_price)",
     "legendFormat": "{{date}} - {{start-price}}"
    }
   ]
  },
  {
   "title": "stock - $active_stocks percantage cahnge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(stock_price{id=~\"$id_of_buy_stock\"}/active_stock_quage{id=~\"$id_of_buy_stock\"} - 1) by (id,date,start_price)",
     "legendFormat": "{{date}} -- {{start_date}}"
    }
   ]
  },
  {
   "title": "stock - $active_stocks value cahnge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(stock_price{id=~\"$id_of_buy_stock\"} -active_stock_quage{id=~\"$id_of_buy_stock\"}) by (id,date,start_price)",
     "legendFormat": "{{date}} - {{start_price}}"
    }
   ]
  }
 ]
}