{
 "title": "Main - Stocks Ozile Made Me",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "symbol", "query": { "query": "" } },
   {
    "name": "active_stocks",
    "query": {
     "query": "label_values(active_stock_quage,symbol)"
    }
   },
   { "name": "shekel_dollar_rate", "query": "3.31" }
  ]
 },
 "panels": [
  {
   "title": "Total bag stocks dollars",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bag stocks shekel by rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "₪" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})) * $shekel_dollar_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "percentage profit on whole bag after taxees ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n/\n\nsum (invested_money_by_dollars{type=\"dollars\"})) - 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "value profit on whole bag after taxees ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n-\n\nsum (invested_money_by_dollars{type=\"dollars\"})) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Timeseries total view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "All bag improvment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})",
     "legendFormat": "After taxes bag"
    },
    {
     "expr": "sum((invested_money_by_dollars{type=\"dollars\"}))",
     "legendFormat": "All bag invasted"
    }
   ]
  },
  {
   "title": "Timeseries percentage profit on whole bag after taxees ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n/\n\nsum (invested_money_by_dollars{type=\"dollars\"})) - 1",
     "legendFormat": "profit by percantage"
    }
   ]
  },
  {
   "title": "value profit on whole bag after taxees ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n-\n\nsum (invested_money_by_dollars{type=\"dollars\"})) ",
     "legendFormat": "profit by value"
    }
   ]
  },
  { "title": "Active Stocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "active_stocks" },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "repeat": "active_stocks",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(stock_price{symbol=\"$active_stocks\"} / active_stock_quage{symbol=\"$active_stocks\"}) -1",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "Active Stocks High view",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(stock_price{symbol=~\".*\"}/active_stock_quage{symbol=~\".*\"} - 1) by (id,symbol,date)",
     "legendFormat": "{{symbol}} -- {{date}}"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "History of done buy Stocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "filterExpression": "symbol =~ \"$symbol\"",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:3001/stocks",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "History of Investing",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://127.0.0.1:3001/invest_history",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "invest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "invested_money_by_dollars{type=\"dollars\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "₪" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "invested_money_by_shekels{type=\"shekels\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Taxes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Rate of taxes out of revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n+ \nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n+\n(((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} )))\n+\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n- \n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n-\n\nsum (invested_money_by_dollars{type=\"dollars\"})))\n\n-\n\n(((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n+\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n- \n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n-\n\nsum (invested_money_by_dollars{type=\"dollars\"})) ))\n\n/\n\n(((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} )))\n-\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n+\n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\n\n\nsum (invested_money_by_dollars{type=\"dollars\"}))))\n",
     "legendFormat": "rate of taxes out of profit"
    }
   ]
  },
  {
   "title": "Total transaction taxes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n+ \nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxes by county",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} )))\n+\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n- \n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n-\n\nsum (invested_money_by_dollars{type=\"dollars\"})))\n\n-\n\n(((sum((invested_money_by_dollars{type=\"dollars\"}\n+\n(profit_by_active_but_not_done_stocks{type=\"dollars\"} * 0.75)))\n+\nsum(\n  active_stock_quage{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n\n- \n\nsum(\n  stock_price{id=~\".*\"}\n  * on(id) group_left(symbol) active_stock_quantity_quage{id=~\".*\"}\n)\n-\nsum(taxes_by_transactions_buy_sum{type=\"dollars\"})\n-\nsum(taxes_by_transactions_sell_sum{type=\"dollars\"})\n)\n-\n\nsum (invested_money_by_dollars{type=\"dollars\"})) )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}